USE [master]
GO
/****** Object:  Database [Terrario_base]    Script Date: 27/6/2024 22:11:32 ******/
CREATE DATABASE [Terrario_base]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Terrario_base', FILENAME = N'C:\SQLData\DATA\Terrario_base.mdf' , SIZE = 8192KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Terrario_base_log', FILENAME = N'C:\SQLData\DATA\Terrario_base_log.ldf' , SIZE = 1024KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Terrario_base] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Terrario_base].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Terrario_base] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Terrario_base] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Terrario_base] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Terrario_base] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Terrario_base] SET ARITHABORT OFF 
GO
ALTER DATABASE [Terrario_base] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Terrario_base] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Terrario_base] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Terrario_base] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Terrario_base] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Terrario_base] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Terrario_base] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Terrario_base] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Terrario_base] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Terrario_base] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Terrario_base] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Terrario_base] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Terrario_base] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Terrario_base] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Terrario_base] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Terrario_base] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Terrario_base] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Terrario_base] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Terrario_base] SET  MULTI_USER 
GO
ALTER DATABASE [Terrario_base] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Terrario_base] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Terrario_base] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Terrario_base] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Terrario_base] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Terrario_base] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Terrario_base] SET QUERY_STORE = ON
GO
ALTER DATABASE [Terrario_base] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Terrario_base]
GO
/****** Object:  Table [dbo].[Hamster]    Script Date: 27/6/2024 22:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hamster](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Peso] [float] NULL,
	[TipoAlimentacion] [int] NULL,
	[Longitud] [float] NULL,
	[EsNocturno] [bit] NULL,
 CONSTRAINT [PK_Hamster] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Raton]    Script Date: 27/6/2024 22:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Raton](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Peso] [float] NULL,
	[TipoAlimentacion] [int] NULL,
	[LargoCola] [float] NULL,
	[EsAlbino] [bit] NULL,
 CONSTRAINT [PK_Raton] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topo]    Script Date: 27/6/2024 22:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Peso] [float] NULL,
	[TipoAlimentacion] [int] NULL,
	[ProfundidadExcavada] [float] NULL,
	[GarrasAfiladas] [bit] NULL,
 CONSTRAINT [PK_Topo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Hamster] ON 

INSERT [dbo].[Hamster] ([Id], [Nombre], [Peso], [TipoAlimentacion], [Longitud], [EsNocturno]) VALUES (1, N'Hammy', 50, 1, 8, 1)
SET IDENTITY_INSERT [dbo].[Hamster] OFF
GO
SET IDENTITY_INSERT [dbo].[Raton] ON 

INSERT [dbo].[Raton] ([Id], [Nombre], [Peso], [TipoAlimentacion], [LargoCola], [EsAlbino]) VALUES (1, N'Jamon', 30, 0, 6, 0)
SET IDENTITY_INSERT [dbo].[Raton] OFF
GO
SET IDENTITY_INSERT [dbo].[Topo] ON 

INSERT [dbo].[Topo] ([Id], [Nombre], [Peso], [TipoAlimentacion], [ProfundidadExcavada], [GarrasAfiladas]) VALUES (1, N'Topon', 80, 2, 12, 1)
SET IDENTITY_INSERT [dbo].[Topo] OFF
GO
USE [master]
GO
ALTER DATABASE [Terrario_base] SET  READ_WRITE 
GO
